artikel/urls.py
from django.urls import path
from .views import ArtikelKategoriListView, ArtikelListView, ArtikelDetailView, ArtikelCreateView, ArtikelManageView, ArtikelDeleteView, ArtikelUpdateView

urlpatterns = [
    path('manage/update/<pk>', ArtikelUpdateView.as_view(), name='update'),
    path('manage/delete/<pk>', ArtikelDeleteView.as_view(), name='delete'),
    path('manage/', ArtikelManageView.as_view(), name='manage'),
    path('tambah/', ArtikelCreateView.as_view(), name='create'),
    path('<page>', ArtikelListView.as_view(), name='list'),
    path('detail/<slug>', ArtikelDetailView.as_view(), name='detail'),
    path('kategori/<kategori>/<page>', ArtikelKategoriListView.as_view(), name = 'category'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from .views import BlogHomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', BlogHomeView.as_view(), name='home'),
    path('artikel/', include(('artikel.urls', 'artikel'), namespace='artikel'))
 ]

artikel/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
class Artikel(models.Model):
    judul = models.CharField(max_length=255)
    isi = models.TextField()
    kategori = models.CharField(max_length=255)
    published = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True, editable=False)
    def save(self):
        self.slug = slugify(self.judul)
        super().save()

    def get_absolute_url(self):
        url_slug = {'slug':self.slug}
        return reverse('artikel:detail', kwargs= url_slug)

    def __str__(self):
        return f"{self.id}. {self.judul}"
    

artikel/forms.py
from django.forms import ModelForm
from .models import Artikel

class ArtikelForm(ModelForm):
    class Meta:
        model = Artikel
        fields = [
            'judul',
            'isi',
            'kategori'
        ]

artikel/views.py
from django.views.generic.edit import DeleteView, UpdateView
from artikel.forms import ArtikelForm
from django.db.models.expressions import OrderBy
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from .models import Artikel
from .forms import ArtikelForm
from django.urls import reverse_lazy
# Create your views here.
#membuatc class kalau bisa satu class utk satu fungsi

class ArtikelUpdateView(UpdateView):
    form_class = ArtikelForm
    model = Artikel
    template_name = 'artikel/artikel_update.html'

class ArtikelDeleteView(DeleteView):
    model = Artikel
    template_name = 'artikel/artikel_delete_confirmation.html'
    success_url = reverse_lazy('artikel:manage')

class ArtikelManageView(ListView):
    model = Artikel
    template_name = 'artikel/artikel_manage.html'
    context_object_name = 'artikel_manage'

class ArtikelCreateView(CreateView):
    form_class = ArtikelForm
    template_name = 'artikel/artikel_create.html'

class ArtikelPerKategori():
    model = Artikel
    def get_latest_artikel_each_kategori(self):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        queryset = []
        for kategori in kategori_list:
            artikel = self.model.objects.filter(kategori=kategori).latest('published')
            queryset.append(artikel)
        # print(queryset)
        return queryset

class ArtikelKategoriListView(ListView):
    model = Artikel
    template_name = "artikel/artikel_kategori_list.html"
    ordering = ['-published']
    context_object_name = 'artikel_list'
    paginate_by = 3
    def get_queryset(self):
        # print(self.kwargs)
        self.queryset = self.model.objects.filter(kategori__iexact = self.kwargs['kategori'])
        # print(artikel_per_kategori)
        return super().get_queryset()
    def get_context_data(self, *args, **kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct().exclude(kategori__iexact = self.kwargs['kategori'])
        self.kwargs.update({'kategori_list':kategori_list})
        kwargs = self.kwargs
        return super().get_context_data(**kwargs)

class ArtikelListView(ListView):
    model = Artikel
    template_name = "artikel/artikel_list.html"
    context_object_name = 'artikel_list' #mengubah nama variabel object_list menjadi artikel_list
    ordering = ['-published'] #dari yang paling terakhir dibuat
    paginate_by = 3
    def get_context_data(self, *args, **kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        self.kwargs.update({'kategori_list':kategori_list})
        kwargs = self.kwargs
        return super().get_context_data(**kwargs)

class ArtikelDetailView(DetailView):
    model = Artikel
    template_name = 'artikel/artikel_detail.html'
    context_object_name = 'artikel'
    def get_context_data(self, *args, **kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        self.kwargs.update({'kategori_list':kategori_list})
        artikel_serupa = self.model.objects.filter(kategori = self.object.kategori).exclude(id = self.object.id)
        self.kwargs.update({'artikel_serupa':artikel_serupa})
        kwargs = self.kwargs
        return super().get_context_data(**kwargs)

blog/views.py
from django.views.generic import TemplateView
from artikel.views import ArtikelPerKategori


class BlogHomeView(TemplateView, ArtikelPerKategori):
    template_name = 'index.html'
    def get_context_data(self):
        querysets = self.get_latest_artikel_each_kategori()
        # print(kategori_list)
        # return super().get_context_data(**kwargs)
        context = {
            'latest_artikel_list':querysets
        }
        return context

artikel/templates/artikel/artikel_create.html
{% extends 'base.html' %}


{% block page_title %}
    Create
{% endblock page_title %}


{% block contents %}
    <h1>Tambah Artikel</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{form.judul.id_for_label}}">{{form.judul.label}}:</label>
            <input type="text" class="form-control" name="{{form.judul.name}}" maxlength="{{form.judul.max}}" required id="form_judul.id_for_label">
        </div>
        <div class="form-group">
            <label for="{{form.isi.id_for_label}}">{{form.isi.label}}:</label>
            <textarea class="form-control" name="{{form.isi.name}}" id="{{form.isi.id_for_label}}" cols="30" rows="10" required></textarea>
        </div>
        <div class="form-group">
            <label for="{{form.kategori.id_for_label}}">{{form.kategori.label}}:</label>
            <input type="text" class="form-control" name="{{form.kategori.name}}" maxlength="{{form.judul.max}}" required id="form_judul.id_for_label">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock contents %}

artikel/templates/artikel/artikel_delete_confirmation.html
{% extends 'base.html' %}


{% block page_title %}
    Delete Artikel
{% endblock page_title %}


{% block contents %}
    <h1>Delete Artikel Confirmation</h1>
    <p>Apakah benar anda ingin menghapus artikel berikut:</p>
    <h3>{{artikel.judul}}</h3>
    <p>{{artikel.published}}</p>
    <form method="POST" action="">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Ya</button>
        <a class="btn btn-danger" href="{% url 'artikel:manage' %}">Tidak</a>
    </form>
{% endblock contents %}
    

artikel/templates/artikel/artikel_detail.html
{% extends 'base.html' %}


{% block page_title %}
    Detail | {{artikel.judul}}
{% endblock page_title %}


{% block contents %}
    <div class="row">
        <div class="col-md-8">
            <h1>{{artikel.judul}}</h1>
            <h5>Kategori : {{artikel.kategori}} | {{artikel.published}}</h5>
            <p>{{artikel.isi}}</p>
        </div>
        <div class="col-sm">
            <h3>Kategori</h3>
            <ul class="list-group list-group-flush">
                {% for kategori in kategori_list %}
                    <li class="list-group-item"><a href="{% url 'artikel:category' kategori 1 %}">{{kategori}}</a></li>
                {% endfor %}
            </ul>
            <br>
            <h3>Artikel Serupa</h3>
            <ul class="list-group list-group-flush">
                {% for artikel in artikel_serupa %}
                    {% if forloop.counter is not 3 %}
                        <li class="list-group-item">
                            <h5><a href="{% url 'artikel:detail' artikel.slug %}">{{artikel.judul}}</a></h5>
                            <p>{{artikel.published|date}}</p>
                        </li>
                    {% endif %}
                {% endfor %}
                <li class="list-group-item"><a href="{% url 'artikel:category' artikel.kategori 1 %}">Selengkapnya</a></li>
            </ul>
                
        </div>
    </div>
{% endblock contents %}
    
    

artikel/templates/artikel/artikel_kategori_list.html
{% extends 'base.html' %}


{% block page_title %}
    Artikel
{% endblock page_title %}
    

{% block contents %}
    <h1>Artikel</h1>
    
    <div class="row">
        <div class="col-md-8">
            <h2 class="border-bottom">Kategori : {{kategori}}</h2>
            {% if is_paginated %}
                <nav aria-label="artikelPage">
                    <ul class="pagination">
            

                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'artikel:category' kategori page_obj.previous_page_number %}">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                    {% endif %}
        
                    
                    {% for page in paginator.page_range %}
                        {% if page is page_obj.number %}
                            <li class="page-item active" aria-current="page">
                                <span class="page-link" href="#">{{page}}<span class="sr-only">(current)</span></span>
                            </li> 
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="{% url 'artikel:category' kategori page %}">{{page}}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    
                    
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'artikel:category' kategori page_obj.next_page_number %}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
                        </li>
                    {% endif %}
                    </ul>
                </nav>
            {% endif %}
            
            {% for artikel in artikel_list %}
                <h3><a class="text-dark" href="{% url 'artikel:detail' artikel.slug %}">{{artikel.judul}}</a></h3>
                <p>{{artikel.published}}</p>
                <p class="border-bottom">{{artikel.isi|truncatewords:50}} <a href="{% url 'artikel:detail' artikel.slug %}">Selengkapnya</a></p>
            {% endfor %}
        </div>
        <div class="col-sm">
            <h3>Kategori Lainnya</h3>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><a href="{% url 'artikel:list' 1 %}"><b>Semua Kategori</b></a></li>
                {% for kategori in kategori_list %}
                <li class="list-group-item"><a href="{% url 'artikel:category' kategori 1%}">{{kategori}}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    
    
    <!-- <p>{{object_list}}</p> -->
    <!-- <p>{{artikel_list}}</p> -->
{% endblock contents %}

artikel/templates/artikel/artikel_list.html
{% extends 'base.html' %}


{% block page_title %}
    Artikel
{% endblock page_title %}
    

{% block contents %}
    <h1>Artikel</h1>
    
    <div class="row">
        <div class="col-md-8">
            {% if is_paginated %}
                <nav aria-label="artikelPage">
                    <ul class="pagination">
            

                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'artikel:list' page_obj.previous_page_number %}">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                    {% endif %}
        
                    
                    {% for page in paginator.page_range %}
                        {% if page is page_obj.number %}
                            <li class="page-item active" aria-current="page">
                                <span class="page-link" href="#">{{page}}<span class="sr-only">(current)</span></span>
                            </li> 
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="{% url 'artikel:list' page %}">{{page}}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    
                    
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'artikel:list' page_obj.next_page_number %}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
                        </li>
                    {% endif %}
                    </ul>
                </nav>
            {% endif %}
            
            {% for artikel in artikel_list %}
                <h3><a class="text-dark" href="{% url 'artikel:detail' artikel.slug %}">{{artikel.judul}}</a></h3>
                <p>Kategori : {{artikel.kategori}} | {{artikel.published}}</p>
                <p class="border-bottom">{{artikel.isi|truncatewords:50}} <a href="{% url 'artikel:detail' artikel.slug %}">Selengkapnya</a></p>
            {% endfor %}
        </div>
        <div class="col-sm">
            <h3>Kategori</h3>
            <ul class="list-group list-group-flush">
                {% for kategori in kategori_list %}
                    <li class="list-group-item"><a href="{% url 'artikel:category' kategori 1 %}">{{kategori}}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    
    
    <!-- <p>{{object_list}}</p> -->
    <!-- <p>{{artikel_list}}</p> -->
{% endblock contents %}

artikel/templates/artikel/artikel_manage.html
{% extends 'base.html' %}


{% block page_title %}
    Manage Artikel
{% endblock page_title %}


{% block contents %}
    <h1>Manage Artikel</h1>
    <table class="table mt-4">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Judul</th>
            <th scope="col">Category</th>
            <th scope="col">Publish</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
            
            {% for artikel in artikel_manage %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{artikel.judul}}</td>
                    <td>{{artikel.kategori}}</td>
                    <td>{{artikel.published}}</td>
                    <td>
                        <a href="{% url 'artikel:update' artikel.id %}" class="btn btn-warning">Edit</a>
                        <a type="button" class="btn btn-danger" href="{% url 'artikel:delete' artikel.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-primary btn-block" href="{% url 'artikel:create' %}">Tambah Artikel</a>
    <br>
{% endblock contents %}
    

artikel/templates/artikel/artikel_update.html
{% extends 'base.html' %}


{% block page_title %}
    Update
{% endblock page_title %}


{% block contents %}
    <h1>Update Artikel</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{form.judul.id_for_label}}">{{form.judul.label}}:</label>
            <input type="text" class="form-control" name="{{form.judul.name}}" maxlength="{{form.judul.max}}" required id="form_judul.id_for_label" value="{{form.judul.value}}">
        </div>
        <div class="form-group">
            <label for="{{form.isi.id_for_label}}">{{form.isi.label}}:</label>
            <textarea class="form-control" name="{{form.isi.name}}" id="{{form.isi.id_for_label}}" cols="30" rows="10" required>{{form.isi.value}}</textarea>
        </div>
        <div class="form-group">
            <label for="{{form.kategori.id_for_label}}">{{form.kategori.label}}:</label>
            <input type="text" class="form-control" name="{{form.kategori.name}}" maxlength="{{form.judul.max}}" required id="form_judul.id_for_label" value="{{form.kategori.value}}">
        </div>
        <button type="submit" class="btn btn-warning">Update</button>
        <a class="btn btn-danger" href="{% url 'artikel:manage' %}">Tidak</a>
    </form>
{% endblock contents %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block page_title %}
        {% endblock page_title %} 
    </title>
    {% include 'snippets/style.html' %}
</head>
<body>
    {% include 'snippets/navbar.html' %}
    <div class="container" style="margin-top: 100px;">
        {% block contents %}
        {% endblock contents %}
    </div>
        

    {% include 'snippets/script.html' %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}


{% block page_title %}
    Home
{% endblock page_title %}
    

{% block contents %}
    <h1>Home</h1>
    <!-- <p>{{latest_artikel_list}}</p> -->
    <div class="row">
        {% for artikel in latest_artikel_list %}
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                <h5 class="card-title"><a href="{% url 'artikel:category' artikel.kategori 1 %}">{{artikel.kategori}}</a></h5>
                <h6 class="card-subtitle mb-2 text-dark">{{artikel.judul}}</h6>
                <h6 class="card-subtitle mb-2 text-dark">{{artikel.published|date}}</h6>
                <p class="card-text">{{artikel.isi|truncatewords:10}}</p>
                <a href="{% url 'artikel:detail' artikel.slug %}" class="card-link">Selengkapnya</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock contents %}
    

templates/snippets/navbar.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'artikel:list' 1 %}">Artikel</a>
                    <!-- 1 berarti default page di 1 -->
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
            </ul>
            <div class="nav-item dropdown ml-auto">
                <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    User
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'artikel:create' %}">Tambah Artikel</a>
                    <a class="dropdown-item" href="{% url 'artikel:manage' %}">Manage Artikel</a>
                </div>
            </div>
        </div>
    </div>
</nav>

templates/snippets/script.html
{% load static %}
<script src="{% static 'vendor/jquery/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

templates/snippets/style.html
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">